# Generated by Django 5.0.1 on 2024-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_reportmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
